import sys
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import Response
from app.report.pdf_generator import generate_pdf_report
from app.risk.charts import (
    generate_risk_chart,
    generate_radar_chart,
    generate_likelihood_impact_matrix,
)
from app.risk.dashboard_metrics import build_dashboard_metrics

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(PROJECT_ROOT))

from backend.schemas import AnalyzeRequest, AnalyzeResponse
from app.agents.orchestrator import run_orchestrator
from app.risk.llm_scoring import score_report_with_llm


api = FastAPI(
    title="AI Risk Advisor API",
    description="FastAPI backend for the AI Risk Advisor multi-agent risk assessment platform.",
    version="1.0.0",
)

from fastapi.middleware.cors import CORSMiddleware

api.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

@api.get("/cors-test")
def cors_test():
    return {
        "cors": "enabled",
        "origins": [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "https://nice-moss-085504f0f.7.azurestaticapps.net"
        ]
    }


@api.get("/")
def root():
    return {
        "service": "AI Risk Advisor API",
        "status": "online",
        "version": "1.0.0",
    }


@api.get("/health")
def health():
    return {"status": "healthy"}


@api.post("/analyze", response_model=AnalyzeResponse)
def analyze(request: AnalyzeRequest):
    if not request.scenario.strip():
        raise HTTPException(status_code=400, detail="Scenario cannot be empty.")

    report = run_orchestrator(request.scenario)
    risk_score = score_report_with_llm(request.scenario, report)

    function_scores = {
        "GOVERN": risk_score.get("govern_score", 0),
        "MAP": risk_score.get("map_score", 0),
        "MEASURE": risk_score.get("measure_score", 0),
        "MANAGE": risk_score.get("manage_score", 0),
    }
    dashboard_metrics = build_dashboard_metrics(risk_score, function_scores)

    return AnalyzeResponse(
        report=report,
        risk_score=risk_score,
        function_scores=function_scores,
        dashboard_metrics=dashboard_metrics,
        live_demo_note="Generated by AI Risk Advisor backend API.",
    )

@api.post("/export-pdf")
def export_pdf(request: AnalyzeRequest):
    if not request.scenario.strip():
        raise HTTPException(status_code=400, detail="Scenario cannot be empty.")

    report = run_orchestrator(request.scenario)
    risk_score = score_report_with_llm(request.scenario, report)

    scores = {
        "GOVERN": risk_score.get("govern_score", 0),
        "MAP": risk_score.get("map_score", 0),
        "MEASURE": risk_score.get("measure_score", 0),
        "MANAGE": risk_score.get("manage_score", 0),
    }
    
    likelihood_score = risk_score.get("likelihood_score", 0)
    impact_score = risk_score.get("impact_score", 0)

    bar_chart_fig = generate_risk_chart(scores)
    radar_chart_fig = generate_radar_chart(scores)
    matrix_chart_fig = generate_likelihood_impact_matrix(likelihood_score, impact_score)

    pdf_bytes = generate_pdf_report(
        question=request.scenario,
        report=report,
        risk_score=risk_score,
        scores=scores,
        bar_chart_fig=bar_chart_fig,
        radar_chart_fig=radar_chart_fig,
        matrix_chart_fig=matrix_chart_fig,
    )

    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={
            "Content-Disposition": "attachment; filename=ai_risk_advisory_report.pdf"
        },
    )