import sys
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(PROJECT_ROOT))

from backend.schemas import AnalyzeRequest, AnalyzeResponse
from app.agents.orchestrator import run_orchestrator
from app.risk.llm_scoring import score_report_with_llm


api = FastAPI(
    title="AI Risk Advisor API",
    description="FastAPI backend for the AI Risk Advisor multi-agent risk assessment platform.",
    version="1.0.0",
)

api.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten later for production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@api.get("/")
def root():
    return {
        "service": "AI Risk Advisor API",
        "status": "online",
        "version": "1.0.0",
    }


@api.get("/health")
def health():
    return {"status": "healthy"}


@api.post("/analyze", response_model=AnalyzeResponse)
def analyze(request: AnalyzeRequest):
    if not request.scenario.strip():
        raise HTTPException(status_code=400, detail="Scenario cannot be empty.")

    report = run_orchestrator(request.scenario)
    risk_score = score_report_with_llm(request.scenario, report)

    function_scores = {
        "GOVERN": risk_score.get("govern_score", 0),
        "MAP": risk_score.get("map_score", 0),
        "MEASURE": risk_score.get("measure_score", 0),
        "MANAGE": risk_score.get("manage_score", 0),
    }

    return AnalyzeResponse(
        report=report,
        risk_score=risk_score,
        function_scores=function_scores,
        live_demo_note="Generated by AI Risk Advisor backend API.",
    )